# Generated by Django 5.1.6 on 2025-03-14 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría del producto')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.CharField(max_length=50, verbose_name='Categoría del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategoria', to='productos.categoriaproducto', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'subcategoria',
                'verbose_name_plural': 'subcategorias',
                'db_table': 'subcategoria_producto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción del producto')),
                ('precio', models.FloatField(max_length=10, verbose_name='Precio del producto')),
                ('imagen', models.ImageField(upload_to='img/img_productos/', verbose_name='Logo del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='productos.categoriaproducto', verbose_name='Categoría del producto')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='establecimiento.establecimiento', verbose_name='Establecimiento')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='productos.subcategoriaproducto', verbose_name='Subcategoría del producto')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='ValoracionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.CharField(max_length=1, verbose_name='Valoración del producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoracion', to='productos.producto', verbose_name='Producto')),
                ('usaurio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoracion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'valoracion',
                'verbose_name_plural': 'valoraciones',
                'db_table': 'valoracion_producto',
            },
        ),
    ]
