# Generated by Django 5.1.6 on 2025-03-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_usaurio_valoracionproducto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='img/img_productos/', verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='subcategoriaproducto',
            name='subcategoria',
            field=models.CharField(max_length=50, verbose_name='Subcategoría del producto'),
        ),
    ]
