# Generated by Django 5.1.6 on 2025-03-15 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orden', models.FloatField(max_length=10, verbose_name='Precio total de la orden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='ProductosOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de productos de la orden')),
                ('precio_total', models.FloatField(blank=True, max_length=10, verbose_name='Precio total del producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_orden', to='ordenes.orden', verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_orden', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'producto_orden',
                'verbose_name_plural': 'producto_ordenes',
                'db_table': 'producto_orden',
            },
        ),
    ]
