# Generated by Django 5.1.6 on 2025-03-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='total_orden',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total de la orden'),
        ),
        migrations.AlterField(
            model_name='productosorden',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total producto orden'),
        ),
    ]
