# Generated by Django 5.1.6 on 2025-03-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_orden_total_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='costo_envio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Costo de envío'),
        ),
        migrations.AddField(
            model_name='orden',
            name='total_carrito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total del carrito'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='total_orden',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total de la orden'),
        ),
    ]
