# Generated by Django 5.1.6 on 2025-03-24 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_orden_costo_envio_orden_total_carrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='costo_envio',
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Creación'),
        ),
    ]
