# Generated by Django 5.1.6 on 2025-03-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_remove_orden_costo_envio_orden_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_orden',
            field=models.CharField(choices=[('01', 'Recibida'), ('02', 'En esperada'), ('03', 'En proceso'), ('04', 'En camino'), ('05', 'Entregada')], default='01', max_length=2),
        ),
    ]
