# Generated by Django 5.1.6 on 2025-03-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avatar_image_filename',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='avatar_name',
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/avatars/', verbose_name='Nombre archivo avatar'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de cliente en Stripe'),
        ),
    ]
