# Generated by Django 5.1.6 on 2025-03-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritocompras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocarrito',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad de productos'),
        ),
        migrations.AddField(
            model_name='productocarrito',
            name='precio_total',
            field=models.FloatField(blank=True, default=0, max_length=10, verbose_name='Precio total del producto'),
            preserve_default=False,
        ),
    ]
