# Generated by Django 5.1.6 on 2025-03-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritocompras', '0004_alter_productocarrito_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocarrito',
            name='precio_total',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Precio total del producto'),
        ),
    ]
