# Generated by Django 5.1.6 on 2025-03-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritocompras', '0006_alter_productocarrito_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='total_carrito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Total del carrito'),
        ),
    ]
