# Generated by Django 5.1.6 on 2025-03-15 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID método pago')),
                ('tipo_tarjeta', models.CharField(choices=[('01', 'VISA'), ('02', 'MASTERCARD'), ('03', 'AMERICAN EXPRESS')], default='01', max_length=2, verbose_name='Tipo tarjeta')),
                ('ultimos_cuatro', models.CharField(max_length=4)),
                ('exp_mes', models.IntegerField(verbose_name='Mes de expiración')),
                ('exp_year', models.IntegerField(verbose_name='Año de expiración')),
                ('is_default', models.BooleanField(default=False, verbose_name='Método de pago por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del método')),
                ('last_use', models.DateTimeField(blank=True, null=True, verbose_name='Último uso de tarjeta')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de productos de la orden')),
                ('precio_total', models.FloatField(blank=True, max_length=10, verbose_name='Precio total del producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'metodo_pago',
                'verbose_name_plural': 'metodos_pago',
                'db_table': 'metodo_pago',
            },
        ),
    ]
