# Generated by Django 5.1.6 on 2025-03-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_remove_metodospago_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodospago',
            name='tipo_tarjeta',
            field=models.CharField(choices=[('01', 'VISA'), ('02', 'MASTERCARD'), ('03', 'AMERICAN EXPRESS'), ('04', 'OTRO')], default='01', max_length=2, verbose_name='Tipo tarjeta'),
        ),
    ]
